### ISSUE TITLE
Alternative way raise on url validator

### ISSUE THREAD

**Issue by wbotelhos** [fnando/validators#17]
Use alternative way syntax raise error, but the old one works nice.

```
Failure/Error: validates :site, tld: true, url: true

ArgumentError:
  Unknown validator: 'TldValidator'
# ./app/models/school.rb:42:in `<class:School>'
# ./app/models/school.rb:3:in `<main>'
# ./spec/models/school/site_spec.rb:5:in `<main>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant #<Class:0x00007fc998ab9550>::TldValidator
#   Did you mean?  School::LengthValidator
#   ./app/models/school.rb:42:in `<class:School>'
```

**Comment by fnando** [comment]
I know it's been a long time, but the right usage would be `validates :site, url: {tld: true}`. That error happens because ActiveModel is trying to load a unregistered validator.
